apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server
  namespace: dop
spec:
  selector:
    matchLabels:
      app: discovery-server
  replicas: 1
  template:
    metadata:
      labels:
        app: discovery-server
    spec:
      containers:
        - name: discovery-server
          image: registry.dop.clsaa.com/dop/discovery-server:<BUILD_TAG>
          resources:
            requests:
              memory: 384Mi
              cpu: 250m
            limits:
              memory: 384Mi
              cpu: 500m
          volumeMounts:
            - name: host-time
              mountPath: /etc/localtime
            - name: host-timezone
              mountPath: /etc/timezone
          ports:
            - containerPort: 8761
      volumes:
        - name: host-time
          hostPath:
            path: /etc/localtime
        - name: host-timezone
          hostPath:
            path: /etc/timezone
      nodeSelector:
        labelName: dop-node2
---
apiVersion: v1
kind: Service
metadata:
  name: discovery-server
  namespace: dop
  labels:
    app: discovery-server
spec:
  type: NodePort
  ports:
  - port: 8761
    protocol: TCP
    targetPort: 8761
  selector:
    app: discovery-server
#---
#apiVersion: extensions/v1beta1
#kind: Ingress
#metadata:
#  name: discovery-server
#  namespace: dop
#spec:
#  rules:
#  - host: 121.42.13.103:30195
#    http:
#      paths:
#      - backend:
#          serviceName: discovery-server
#          servicePort: 8761
