apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-server
  namespace: dop
spec:
  selector:
    matchLabels:
      app: user-server
  replicas: 1
  template:
    metadata:
      labels:
        app: user-server
    spec:
      containers:
        - name: user-server
          imagePullPolicy: Always
          image: registry.dop.clsaa.com/dop/user-server:<BUILD_TAG>
          resources:
            requests:
              memory: 512Mi
              cpu: 250m
            limits:
              memory: 512Mi
              cpu: 500m
          volumeMounts:
            - name: host-time
              mountPath: /etc/localtime
            - name: host-timezone
              mountPath: /etc/timezone
          ports:
            - containerPort: 13100
      volumes:
        - name: host-time
          hostPath:
            path: /etc/localtime
        - name: host-timezone
          hostPath:
            path: /etc/timezone
      nodeSelector:
        labelName: dop-node2
---
apiVersion: v1
kind: Service
metadata:
  name: user-server
  namespace: dop
  labels:
    app: user-server
spec:
  ports:
    - port: 13100
      protocol: TCP
      targetPort: 13100
  selector:
    app: user-server
