apiVersion: apps/v1
kind: Deployment
metadata:
  name: defect-location-server
  namespace: dop
spec:
  selector:
    matchLabels:
      app: defect-location-server
  replicas: 1
  template:
    metadata:
      labels:
        app: defect-location-server
    spec:
      containers:
        - name: algorithm
          imagePullPolicy: Always
          image: 172.29.7.157:85/dop/defect-location-server-algorithm:<BUILD_TAG>
          ports:
            - containerPort: 5005
          volumeMounts:
            - name: project-data
              mountPath: /tmp
            - name: code-data
              mountPath: /code/src/train
        - name: backend
          imagePullPolicy: Always
          image: 172.29.7.157:85/dop/defect-location-server-backend:<BUILD_TAG>
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: project-data
              mountPath: /tmp
      volumes:
        - name: project-data
          emptyDir: {}
        - name: code-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: defect-location-server
  namespace: dop
  labels:
    app: defect-location-server
spec:
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: defect-location-server
