apiVersion: apps/v1
kind: Deployment
metadata:
  name: audit-server
  namespace: dop
spec:
  selector:
    matchLabels:
      app: audit-server
  replicas: 1
  template:
    metadata:
      labels:
        app: audit-server
    spec:
      containers:
        - name: audit-server
          imagePullPolicy: Always
          image: registry.dop.clsaa.com/dop/audit-server:<BUILD_TAG>
          resources:
            requests:
              memory: 384Mi
              cpu: 250m
            limits:
              memory: 384Mi
              cpu: 500m
          volumeMounts:
            - name: host-time
              mountPath: /etc/localtime
            - name: host-timezone
              mountPath: /etc/timezone
          ports:
            - containerPort: 13500
      volumes:
        - name: host-time
          hostPath:
            path: /etc/localtime
        - name: host-timezone
          hostPath:
            path: /etc/timezone
---
apiVersion: v1
kind: Service
metadata:
  name: audit-server
  namespace: dop
  labels:
    app: audit-server
spec:
  ports:
    - port: 13500
      protocol: TCP
      targetPort: 13500
  selector:
    app: audit-server
