apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin-server
  namespace: dop
spec:
  selector:
    matchLabels:
      app: zipkin-server
  replicas: 1
  template:
    metadata:
      labels:
        app: zipkin-server
    spec:
      containers:
        - name: zipkin-server
          imagePullPolicy: Always
          image: 172.29.7.157:85/dop/zipkin-server:<BUILD_TAG>
          resources:
            requests:
              memory: 512Mi
              cpu: 250m
            limits:
              memory: 512Mi
              cpu: 500m
          volumeMounts:
            - name: host-time
              mountPath: /etc/localtime
            - name: host-timezone
              mountPath: /etc/timezone
          ports:
            - containerPort: 9000
      volumes:
        - name: host-time
          hostPath:
            path: /etc/localtime
        - name: host-timezone
          hostPath:
            path: /etc/timezone
---
apiVersion: v1
kind: Service
metadata:
  name: zipkin-server
  namespace: dop
  labels:
    app: zipkin-server
spec:
  ports:
    - port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    app: zipkin-server
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zipkin-server
  namespace: dop
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: zipkin.devopsplus.com.cn
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: zipkin-server
                port:
                  number: 9000
