apiVersion: apps/v1
kind: Deployment
metadata:
  name: permission-server
  namespace: dop
spec:
  selector:
    matchLabels:
      app: permission-server
  replicas: 1
  template:
    metadata:
      labels:
        app: permission-server
    spec:
      containers:
        - name: permission-server
          imagePullPolicy: Always
          image: 172.29.7.157:85/dop/permission-server:<BUILD_TAG>
          resources:
            requests:
              memory: 384Mi
              cpu: 250m
            limits:
              memory: 384Mi
              cpu: 500m
          volumeMounts:
            - name: host-time
              mountPath: /etc/localtime
            - name: host-timezone
              mountPath: /etc/timezone
          ports:
            - containerPort: 13300
      volumes:
        - name: host-time
          hostPath:
            path: /etc/localtime
        - name: host-timezone
          hostPath:
            path: /etc/timezone
---
apiVersion: v1
kind: Service
metadata:
  name: permission-server
  namespace: dop
  labels:
    app: permission-server
spec:
  ports:
    - port: 13300
      protocol: TCP
      targetPort: 13300
  selector:
    app: permission-server
