apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-server
  namespace: dop
spec:
  selector:
    matchLabels:
      app: gateway-server
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway-server
    spec:
      containers:
        - name: gateway-server
          imagePullPolicy: Always
          image: registry.dop.clsaa.com/dop/gateway-server:<BUILD_TAG>
          resources:
            requests:
              memory: 384Mi
              cpu: 250m
            limits:
              memory: 384Mi
              cpu: 500m
          volumeMounts:
            - name: host-time
              mountPath: /etc/localtime
            - name: host-timezone
              mountPath: /etc/timezone
          ports:
            - containerPort: 8888
      volumes:
        - name: host-time
          hostPath:
            path: /etc/localtime
        - name: host-timezone
          hostPath:
            path: /etc/timezone
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-server
  namespace: dop
  labels:
    app: gateway-server
spec:
  ports:
    - port: 14258
      protocol: TCP
      targetPort: 8888
  selector:
    app: gateway-server
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
 name: gateway-server
 namespace: dop
spec:
 rules:
   - host: open.dop.clsaa.com
     http:
       paths:
         - backend:
             serviceName: gateway-server
             servicePort: 14258
