apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-server
  namespace: dop
spec:
  selector:
    matchLabels:
      app: gateway-server
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway-server
    spec:
      containers:
        - name: gateway-server
          imagePullPolicy: Always
          image: 172.29.7.157:85/dop/gateway-server:<BUILD_TAG>
          resources:
            requests:
              memory: 384Mi
              cpu: 250m
            limits:
              memory: 384Mi
              cpu: 500m
          volumeMounts:
            - name: host-time
              mountPath: /etc/localtime
            - name: host-timezone
              mountPath: /etc/timezone
          ports:
            - containerPort: 8888
      volumes:
        - name: host-time
          hostPath:
            path: /etc/localtime
        - name: host-timezone
          hostPath:
            path: /etc/timezone
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-server
  namespace: dop
  labels:
    app: gateway-server
spec:
  ports:
    - port: 14258
      protocol: TCP
      targetPort: 8888
  selector:
    app: gateway-server
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: gateway-server
 namespace: dop
 annotations:
  kubernetes.io/ingress.class: "nginx"
  nginx.ingress.kubernetes.io/enable-cors: "true"
  nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization,X-Login-User,X-Login-Token"
  nginx.ingress.kubernetes.io/proxy-connect-timeout: "6000"
  nginx.ingress.kubernetes.io/proxy-read-timeout: "60000"
  nginx.ingress.kubernetes.io/proxy-send-timeout: "60000"
spec:
 rules:
   - host: open.devopsplus.com.cn
     http:
       paths:
         - path: /
           pathType: Prefix
           backend:
             service:
               name: gateway-server
               port:
                 number: 14258
