name: mirror to doporg repo
on: [ push, delete, create ]
jobs:
  git-mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@v1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DOPORG_RSA_PRIVATE_KEY }}
        with:
          source-repo: "git@github.com:nju-softeng/dop-server.git"
          destination-repo: "git@github.com:doporg/dop.git"
